name: CI
on: [push, pull_request]
permissions:
  contents: read
  id-token: write
jobs:
  ci:
    uses: edithatogo/repository-standards/.github/workflows/node-ci.yml@6169e53d0ae27bdbf45ca416c8548f78526463db # main